Desktop version of my portfolio
Ochiengsteven/portfolio pull request #11
Opened 2023-03-31 10:58 UTC by Ochiengsteven

2023-03-31 11:24 UTC, iambenkis requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Ochiengsteven
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @iambenkis  when you comment, so I can receive the notification or use Slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 11:24 UTC, iambenkis commented on style.css
>    align-items: center;
- [ ] Good job creating a beautiful desktop version ever, however as required , the  value for min-width property should be in range of 768px or wider, that means that the nav-bar should not be visible for screens in the range of 767px and smaller 👍 , kindly change that 
- [ ] Also make sure that this navbar is centered, so it sticks to the Figma design 👍 

![Capture 1](https://user-images.githubusercontent.com/80458199/229105604-7f90f4cc-a6b3-4d22-849c-51a1eec51c30.PNG)

2023-03-31 11:24 UTC, iambenkis commented on index.html
>                  <div class="second"></div>
- [ ] For semantic it could be better to use the text `My recent works` in one `h3` and make sure the word spacing corresponded to the one used in the Figma design 👍 

![Capture 3](https://user-images.githubusercontent.com/80458199/229105961-3d9d6f90-1ca1-4fe8-893d-c50f6533d042.PNG)

2023-03-31 11:24 UTC, iambenkis commented on index.html
>                      <img src="images/work1.png" alt="">
- [ ] Your work section is beautifully well set, however as required , the  value for min-width property should be in range of 768px or wider, that means that the project section should not have a good look even  for all the screens in the range of 768px and wider 👍 , kindly change that to make your portfolio more  screens responsive 💯 

![Capture 2](https://user-images.githubusercontent.com/80458199/229106461-8b8a8933-c684-4716-ad1f-6793db9639c1.PNG)

2023-03-31 11:24 UTC, iambenkis commented on index.html
> -                    </li>
- [ ] Kindly add the buttons attribute hover, pressed, active tot this button 👍  , to make the use know it is clickable 
![Capture 6](https://user-images.githubusercontent.com/80458199/229106855-c0b13bd3-bdd5-45e3-998c-d48e08fffaca.PNG)

2023-03-31 11:24 UTC, iambenkis commented on index.html
>          </div>
- [ ] As require for this milestone,  your design should stick as much as possible to the Figma design , Kindly make sure the spacing between the elements present on the image below sticks to the Figma design. Always see requirements as client's need you have to meet 👍 
![Capture 7](https://user-images.githubusercontent.com/80458199/229107586-47f07601-6f42-467c-b8e9-cd9383b721ff.PNG)

2023-04-01 09:11 UTC, tufoinnkuo10 requested changes
Hi @Ochiengsteven 

great job so far . There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ great responsive design

Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-04-01 09:11 UTC, tufoinnkuo10 commented on index.html
>                          <button class="btn2" type="submit">Get in touch</button>
- [ ] please like the previous reviewer noted, Kindly add the buttons attribute ` pressed`, to this button 👍, to make the user know when clicked

![Screenshot (932)](https://user-images.githubusercontent.com/65298048/229277049-f53e1fdc-31b0-43e2-b0bf-5be93a913783.png)

2023-04-01 09:11 UTC, tufoinnkuo10 commented on index.html
>                          <textarea name="user-message" maxlength="500" id="msg" cols="50" rows="5" placeholder="Hey I’d like to connect to..." required></textarea>
- [ optional] your desktop contact section is missing the background design
- [optional] please kindly align the form and text in the contact section with the cards above it like in the original design
![Screenshot (931)_LI](https://user-images.githubusercontent.com/65298048/229276696-364fac8c-acdd-49d2-82ee-6ff2cb9b4eee.jpg)

2023-04-01 09:11 UTC, tufoinnkuo10 commented on style.css
>    flex-wrap: wrap;
- [ ] great job so far. please like the previous reviewer noted, on screens less than 768px(mobile screen) the desktop nav links should not be visible. please fix that. 

your design             |  figma
:-------------------------:|:-------------------------:
![Screenshot (929)_LI](https://user-images.githubusercontent.com/65298048/229276327-0e84f579-c899-4c69-a786-c5d106d14f55.jpg)  |  ![Screenshot (930)](https://user-images.githubusercontent.com/65298048/229276342-2cbdf2e0-43e2-4aea-a760-37b6b38000b9.png)

2023-04-01 11:53 UTC, Trast00 requested changes
# Change Required ♻️ 
Hi @Ochiengsteven , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost-there-reach](https://user-images.githubusercontent.com/74411135/225062441-793da0f4-3ef1-4d98-bee9-9c200c7121a7.gif)

## Highlights
- Project look awsome 🍏 🌷 
- Code is clean and well organized 🧼 💯 

 ## Required Changes ♻️
_Check the comments under the review._

- Please consider implementing all the change I left below (inline comment).
**(Here is the  [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1-1471&t=yDKg5dMjRcmmZ2y5-0) mentionned in the inline comment)**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@Trast00) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 11:53 UTC, Trast00 commented on index.html
>                          <button class="btn2" type="submit">Get in touch</button>
Great job implementing the hover interaction on project section buttons 👍 💪 
- [ ] Kindly, as mentioned by the previous reviwer. Make sure all buttons (so also this button **Get in touch**) have button interaction like hover, enabled, pressed. You can do that by using the pseudo class `:hover` for the `hover` interaction, `:active` for the `enabled` interaction, `:focus` for the `pressed` interaction.  This will make your project way more prettier which will improve the user experience 📱  😄 👍 
**Figma design**
![image](https://user-images.githubusercontent.com/74411135/229286612-c24cb7b8-1bbf-4a5e-9d7e-414c76fa2602.png)

2023-04-01 11:53 UTC, Trast00 commented on index.html
> +                <p>Hello I’m a software developer! I can help you build a product, feature or website Look through some of my work and experience! If you like what you see and have a project you need
- [ ] **[OPTIONAL]** Please consider adding background image to your about section. 
**Your project design**
![image](https://user-images.githubusercontent.com/74411135/229286793-460deef9-8f0e-4d45-a151-7b47a2dcb731.png)

**Figma design**
![image](https://user-images.githubusercontent.com/74411135/229286801-fa9b27dc-28b0-42d5-89b3-34565264e918.png)

This will make your project prettier and make the user know your a awesome developper as you can precisly follow a professional web developer design 😃 💪

2023-04-01 11:53 UTC, Trast00 commented on index.html
> +
- [ ] **[OPTIONAL]** Please consider to add background image to match the figma design. 
**Your project design**
![image](https://user-images.githubusercontent.com/74411135/229286764-f11b5881-777a-46b1-8be4-b86cba3c807f.png)

**Figma design**
![image](https://user-images.githubusercontent.com/74411135/229286733-db837f06-5a55-4a0c-8bd0-9b5bc43c19d1.png)


This will make your project prettier and make the user know your a awesome developper as you can precisly follow a professional web developer design 😃 💪

2023-04-01 11:53 UTC, Trast00 commented on index.html
> +                        </ul>
- [ ] **[OPTIONAL]** Please make sure the work section card match the figma design even when resized **as mentioned by the previous reviewer**.
**Your project design**
![image](https://user-images.githubusercontent.com/74411135/229286857-06fe5203-5ed7-4cd2-b577-ea8776d559b3.png)

**Figma design**
![image](https://user-images.githubusercontent.com/74411135/229286903-ec9b1310-4f20-4e48-bd9a-e13f7408c26d.png)

This will make your project look way more prettier 😄 🌹 and demontrate a great skill on CSS 💪

2023-04-01 11:53 UTC, Trast00 commented on index.html
>          <label for="toggler"><i class="fa-solid fa-bars"></i></label>
- [ ] Please like the previous reviwer said, make sure on screen on screens less than 768px(mobile screen) the desktop navigation is hidden and the mobile menu is visible.
> great job so far. please like the previous reviewer noted, on screens less than 768px(mobile screen) the desktop nav links should not be visible. please fix that.

This will make your project way more prettier which will improve the user experience 📱  😄 👍

2023-04-01 15:42 UTC, Trast00 approved these changes
# Approved 🟢
Hi @Ochiengsteven, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :ship: 
Congratulations! 🎉 
![allfather-approves-approved](https://user-images.githubusercontent.com/74411135/225065704-3948f35e-94b9-4440-a31a-29bba50b3c4d.gif)

## Highlights
- Project look awesome 🍏 🌷 
- Code is clean and well organized 🧼 💯 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

- **[OPTIONAL]** Please, I highly suggest implementing optional changes I noted during my previous review. These changes are projected requirements marked as optional as they have been missed by the reviewer before me. Remember, this project is your portfolio and will be extremely important 🆘. Implement these changes will make your project way more professional 😺 💻 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@Trast00) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-03 15:09 UTC, merged