Contact form for my portfolio
Ochiengsteven/portfolio pull request #8
Opened 2023-03-28 13:52 UTC by Ochiengsteven

contact form for my portfolio made with HTML and CSS only.

- I used flexbox
- I used forms

2023-03-28 17:08 UTC, NahnahAJ reviewed
## Project Status: INVALIDATED :red_circle: 
Hi @Ochiengsteven , 

While you made a great effort in this project, I can't go ahead and review your code.
<img src="https://media2.giphy.com/media/TiUYdWptTqn8yOk1Dp/giphy.gif"/>

## Invalid Code Review Request

- This is because you have submitted a project that is a pair-programming activity but I only see a commits from you. Please note that this milestone is a [pair-programming activity](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#work-and-submission-mode) and hence requires commits from both you and your partner/partners :100: 
- If for some other reasons, you had to work alone, then kindly attach a screenshot of the email you received from student success that confirms you were asked to work alone in the pull request :+1: 
- Your Commit History
![image](https://user-images.githubusercontent.com/102699958/228315178-e94911a4-45b4-400f-8c6e-cb611cc678ed.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-29 09:43 UTC, OyePriscilla requested changes
Hi @Ochiengsteven 👏 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Create forms with HTML5 ✔️ 
Collect data by using the [Formspree service](https://formspree.io/html). ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [optional] **Please kindly remove this repeated text from your Readme file.** 👍 
<img width="646" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/228494398-cf8943b1-6c6b-4697-a861-0116cc87e8f7.png">

- [optional] **I think you can remove the live demo text from the table of content of the Readme file and remember to replace it when you have a deployed live demo. All these will make your repo engaging if implemented**. ℹ️   

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 09:43 UTC, OyePriscilla commented on index.html
> +                    </li>
- [ ] Please kindly ensure that this input field can only take maximum of 30 characters according to the project requirement. 👍

2023-03-29 09:43 UTC, OyePriscilla commented on index.html
> +                    </li>
- [ ] Kindly validate all the fields so that a user cannot submit the form if one or more of the fields is empty. 👍

2023-03-29 09:43 UTC, OyePriscilla commented on index.html
> +                        <button class="btn2">Get in touch</button>
- [ ] Please kindly add the "type=submit" to this button element, it defines a submit button which submits all form values to a form-handler. 👍 
- [ ] Kindly implement the correct button interactions according to the given template also. 👍 

## Figma design
<img width="283" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/228491911-5fad80c5-22d3-4132-b716-4c029740be8d.png">

2023-03-29 09:43 UTC, OyePriscilla commented on index.html
> +        </ul>
- [x] Please kindly add this shape and ensure to reduce the size of the social media icons according to the given template. 👍 

##Figma design
<img width="282" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/228354721-6bed09c6-582a-4f09-916f-19d1c1b12c06.png">

2023-03-29 09:43 UTC, OyePriscilla commented on index.html
> +            <h3>I'm always interested in hearing about new projects, so if you'd like to chat please get in touch.</h3>
- [ ] Please ensure to increase the padding-top and padding-bottom according to the design. 👍

2023-03-29 09:43 UTC, OyePriscilla commented on style.css
> +}
- [ ] In accordance to CSS best practices, I observed that you're repeating code here. Kindly make the necessary adjustment. ℹ️ 
```suggestion
.container-form input[type="text"],
.container-form input[type="email"] {
  border: 1px solid #d0d9d4;
  background-color: #fff;
  padding: 10px;
  border-radius: 5px;
  font-family: 'Inter', sans-serif;
  width: 300px;
}
```

2023-03-29 09:43 UTC, OyePriscilla commented on index.html
> +                        <textarea name="user-message" id="msg" cols="30" rows="10" placeholder="Hey I’d like to connect to..."></textarea>
- [ ] Please kindly ensure that this input field can only take maximum of 500 characters according to the project requirement. 👍

2023-03-29 11:41 UTC, joel-kalema approved these changes
Hi @Ochiengsteven 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights
Linters are passing 👍 
The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 11:41 UTC, joel-kalema commented on index.html
> +                <h3>My Recent<br>Works</h3>
- [ ] [OPTIONAL]  Kindly, make sure you stuck to the design as much as possible (font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48-988&t=7V3y8z3F5uwwsjzJ-0) as it is [required](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#:~:text=You%20must%20stick%20to%20the%20design%20as%20much%20as%20possible%20(e.g.%2C%20font%2C%20colors%2C%20images%2C%20text%2C%20margins)%20using%20the%20templates%20in%20Figma.) 👍

> | | Figma template | | Your project | |
> |-|---------|-|--------|-|
> | |![Capture0](https://user-images.githubusercontent.com/57408419/228523456-87d5af11-eaf4-48ba-8f07-94d85ed3a1ec.JPG)| |![Capture](https://user-images.githubusercontent.com/57408419/228523550-a23bf3b1-a1aa-42c4-b55c-6460ef837c80.JPG)| |

> | | Figma template | | Your project | |
> |-|---------|-|--------|-|
> | |![Capture0](https://user-images.githubusercontent.com/57408419/228524549-0fb4d113-b3b1-4213-bc03-07c505672b94.JPG)| |![Capture](https://user-images.githubusercontent.com/57408419/228524629-546ff6bc-c253-4d11-9f8b-88b5015342e4.JPG)| |

2023-03-29 11:55 UTC, merged